"""Tests for the Python implementations wrapped by Numba dispatchers.

The public, compiled call paths are covered elsewhere. Exercising ``py_func``
here both checks the underlying algorithms directly and keeps their branches
visible to coverage.py, which cannot trace machine code generated by Numba.
"""

import numpy as np

from superstats.simulation.cognitive.cdm import sample_cdm
from superstats.simulation.cognitive.ddm import sample_ddm
from superstats.simulation.cognitive.rdm import sample_rdm
from superstats.transition.stochastic.auto_regression import _one_step_ar1, _sample_ar1
from superstats.transition.stochastic.gaussian_process import sample_gaussian_process
from superstats.transition.stochastic.jump import _one_step_jump, _sample_jump_process
from superstats.transition.stochastic.kernel.linear import get_linear_kernel
from superstats.transition.stochastic.kernel.periodic import build_abs_dist_mat, get_periodic_kernel
from superstats.transition.stochastic.kernel.rbf import build_sq_dist_mat, get_rbf_kernel
from superstats.transition.stochastic.levy_flight import (
    _one_step_levy_flight,
    _sample_alpha_stable,
    _sample_levy_flight,
)
from superstats.transition.stochastic.ornstein_uhlenbeck import _one_step_ou, _sample_ou
from superstats.transition.stochastic.random_walk import _one_step_random_walk, _sample_random_walk


def sigmoid(values):
    return 1.0 / (1.0 + np.exp(-np.asarray(values)))


def test_python_ddm_covers_both_boundaries_and_timeout():
    result = sample_ddm.py_func(
        v=np.array([2.0, -2.0, 0.0]),
        a=np.array([1.0, 1.0, 1e6]),
        tau=np.array([0.1, 0.2, 0.3]),
        bias=np.full(3, 0.5),
        sigma=0.0,
        dt=1.0,
        max_steps=1,
    )

    np.testing.assert_array_equal(result["choice"], [1.0, 0.0, -1.0])
    np.testing.assert_allclose(result["response_time"], [1.1, 1.2, -1.0])


def test_python_cdm_covers_crossing_and_timeout():
    result = sample_cdm.py_func(
        v_angle=np.array([np.pi / 2, 0.0]),
        v_length=np.array([2.0, 0.0]),
        a=np.array([1.0, 1e6]),
        tau=np.array([0.25, 0.0]),
        sigma=0.0,
        dt=1.0,
        max_steps=1,
    )

    np.testing.assert_allclose(result["response_time"], [1.25, -5.0])
    np.testing.assert_allclose(result["choice"], [np.pi / 2, -5.0])


def test_python_rdm_covers_default_correct_accumulator_and_timeout():
    result = sample_rdm.py_func(
        v_base=np.array([2.0, 0.0]),
        v_diff=np.array([2.0, 0.0]),
        a_base=np.array([1.0, 1e6]),
        tau=np.array([0.1, 0.0]),
        bias=np.ones(2),
        sigma_diff=np.zeros(2),
        sigma_base=0.0,
        dt=1.0,
        max_steps=1,
    )

    np.testing.assert_array_equal(result["choice"], [0.0, -1.0])
    np.testing.assert_allclose(result["response_time"], [1.1, -1.0])


def test_python_rdm_respects_explicit_correct_accumulator():
    result = sample_rdm.py_func(
        v_base=np.array([0.0]),
        v_diff=np.array([4.0]),
        a_base=np.array([1.0]),
        tau=np.array([0.0]),
        bias=np.ones(1),
        sigma_diff=np.zeros(1),
        correct_idx=np.array([1.0]),
        sigma_base=0.0,
        dt=1.0,
        max_steps=1,
    )

    np.testing.assert_array_equal(result["choice"], [1.0])


def test_python_transition_rollouts_follow_zero_noise_equations():
    bounds = np.array([0.0, 1.0])

    random_walk = _sample_random_walk.py_func(
        np.array([[0.0, np.nan, np.nan]]),
        np.array([0.0]),
        np.array([1.0]),
        bounds,
    )
    ar1 = _sample_ar1.py_func(
        np.array([[2.0, np.nan, np.nan]]),
        np.array([0.0]),
        np.array([0.5]),
        np.array([0.0]),
        bounds,
    )
    ou = _sample_ou.py_func(
        np.array([[2.0, np.nan, np.nan]]),
        np.array([0.0]),
        np.array([0.5]),
        np.array([0.0]),
        bounds,
    )
    levy = _sample_levy_flight.py_func(
        np.array([[0.0, np.nan, np.nan]]),
        np.array([0.0]),
        np.array([1.0]),
        np.array([1.5]),
        np.array([0.0]),
        bounds,
    )

    np.testing.assert_allclose(random_walk[0], sigmoid([0.0, 1.0, 2.0]))
    np.testing.assert_allclose(ar1[0], sigmoid([2.0, 1.0, 0.5]))
    np.testing.assert_allclose(ou[0], sigmoid([2.0, 1.0, 0.5]))
    np.testing.assert_allclose(levy[0], sigmoid([0.0, 1.0, 2.0]))


def test_python_jump_rollout_covers_jump_and_stay_paths():
    result = _sample_jump_process.py_func(
        np.array([[0.0, np.nan, np.nan], [0.0, np.nan, np.nan]]),
        np.array([1.0, 0.0]),
        np.array([[1.0, 2.0], [3.0, 4.0]]),
        np.array([0.0, 1.0]),
    )

    np.testing.assert_allclose(result[0], sigmoid([0.0, 1.0, 2.0]))
    np.testing.assert_allclose(result[1], sigmoid([0.0, 0.0, 0.0]))
    assert _one_step_jump.py_func(2.0, 1.0, 5.0) == 5.0
    assert _one_step_jump.py_func(2.0, 0.0, 5.0) == 2.0


def test_python_one_step_transition_equations_with_zero_noise():
    assert _one_step_random_walk.py_func(2.0, 0.0, 1.0) == 3.0
    assert _one_step_ar1.py_func(2.0, 0.0, 0.5, 1.0) == 2.0
    assert _one_step_ou.py_func(2.0, 0.0, 0.5, 0.0) == 1.0
    assert _one_step_levy_flight.py_func(2.0, 0.0, 1.0, 1.5, 0.0) == 3.0


def test_python_alpha_stable_sampler_handles_special_and_general_cases():
    assert np.isfinite(_sample_alpha_stable.py_func(1.0, 0.25, 1.0))
    assert np.isfinite(_sample_alpha_stable.py_func(1.5, 0.25, 1.0))
    assert _sample_alpha_stable.py_func(1.5, 0.0, 0.0) == 0.0


def test_python_covariance_kernels_match_closed_form_values():
    sq_dist = build_sq_dist_mat.py_func(3)
    abs_dist = build_abs_dist_mat.py_func(3)
    expected_dist = np.array([[0.0, 0.5, 1.0], [0.5, 0.0, 0.5], [1.0, 0.5, 0.0]])
    np.testing.assert_allclose(abs_dist, expected_dist)
    np.testing.assert_allclose(sq_dist, expected_dist**2)

    linear = get_linear_kernel.py_func(3, np.array([2.0]))
    rbf = get_rbf_kernel.py_func(3, np.array([0.5]), np.array([2.0]))
    periodic = get_periodic_kernel.py_func(
        3,
        np.array([0.5]),
        np.array([1.0]),
        np.array([2.0]),
    )

    np.testing.assert_allclose(linear[0], 2.0 * np.outer([0.0, 0.5, 1.0], [0.0, 0.5, 1.0]))
    np.testing.assert_allclose(np.diag(rbf[0]), 4.0)
    np.testing.assert_allclose(np.diag(periodic[0]), 4.0)
    np.testing.assert_allclose(periodic[0, 0, 2], 4.0)


def test_python_gaussian_process_rollout_returns_finite_bounded_values():
    result = sample_gaussian_process.py_func(
        local_params=np.empty((2, 3)),
        start=np.array([0.0, 1.0]),
        kernel_mat=np.broadcast_to(np.eye(3), (2, 3, 3)),
        bounds=np.array([-2.0, 3.0]),
        noise=1e-9,
    )

    assert result.shape == (2, 3)
    assert np.all(np.isfinite(result))
    assert np.all((-2.0 < result) & (result < 3.0))
