"""Default configuration values used across superstats."""

from .network_defaults import (
    DEFAULT_RECURRENT_NETWORK,
    DEFAULT_TRANSFORMER_NETWORK,
    DEFAULT_COUPLING_FLOW,
    DEFAULT_CONSISTENCY_MODEL,
)

from .color_palette import BASE_COLOR, METRIC_COLORS, CATEGORICAL_PALETTE

__all__ = [
    "DEFAULT_RECURRENT_NETWORK",
    "DEFAULT_TRANSFORMER_NETWORK",
    "DEFAULT_COUPLING_FLOW",
    "DEFAULT_CONSISTENCY_MODELBASE_COLOR",
    "METRIC_COLORS",
    "CATEGORICAL_PALETTE",
]
