"""Default configuration values used across superstats."""

from .network_defaults import (
    DEFAULT_RECURRENT_NETWORK,
    DEFAULT_TRANSFORMER_NETWORK,
    DEFAULT_COUPLING_FLOW,
    DEFAULT_CONSISTENCY_MODEL,
)

from .transition_defaults import (
    DEFAULT_STOCHASTIC_HYPER_PRIORS,
    DEFAULT_DETERMINISTIC_HYPER_PRIORS,
    DEFAULT_BOUNDS,
    DEFAULT_INITIAL_PRIOR,
)

from .plotting import (
    AGGREGATE_PLOT_WIDTH,
    BASE_COLOR,
    BASE_COL_WIDTH,
    BASE_ROW_HEIGHT,
    CATEGORICAL_PALETTE,
    DIST_ALPHA,
    HSPACE,
    JOINT_HSPACE,
    LABEL_FONTSIZE,
    LABEL_PAD,
    METRIC_COLORS,
    OVERLAY_DIST_ALPHA,
    TICK_FONTSIZE,
    TITLE_FONTSIZE,
    UNCERTAINTY_BAND_LABELS,
    UNCERTAINTY_INTERVAL_LABELS,
    WSPACE,
    Y_LABEL_PAD,
    METRIC_LABELS,
)

from .augmentation_defaults import DEFAULT_P_MISSING_PRIOR, DEFAULT_P_CONTAMINATED_PRIOR

__all__ = [
    "DEFAULT_RECURRENT_NETWORK",
    "DEFAULT_TRANSFORMER_NETWORK",
    "DEFAULT_COUPLING_FLOW",
    "DEFAULT_CONSISTENCY_MODEL",
    "DEFAULT_STOCHASTIC_HYPER_PRIORS",
    "DEFAULT_DETERMINISTIC_HYPER_PRIORS",
    "DEFAULT_BOUNDS",
    "DEFAULT_INITIAL_PRIOR",
    "AGGREGATE_PLOT_WIDTH",
    "BASE_COLOR",
    "BASE_COL_WIDTH",
    "BASE_ROW_HEIGHT",
    "METRIC_COLORS",
    "OVERLAY_DIST_ALPHA",
    "CATEGORICAL_PALETTE",
    "DIST_ALPHA",
    "HSPACE",
    "JOINT_HSPACE",
    "LABEL_FONTSIZE",
    "LABEL_PAD",
    "TICK_FONTSIZE",
    "TITLE_FONTSIZE",
    "UNCERTAINTY_BAND_LABELS",
    "UNCERTAINTY_INTERVAL_LABELS",
    "WSPACE",
    "Y_LABEL_PAD",
    "METRIC_LABELS",
    "DEFAULT_P_MISSING_PRIOR",
    "DEFAULT_P_CONTAMINATED_PRIOR",
]
