from typing import Tuple
import numpy as np
from numba import njit, prange

from .transition import Transition
from superstats.utils.helpers import scaled_sigmoid
from superstats.prior import Prior


@njit(parallel=True, fastmath=True)
def sample_random_walk(
    local_params: np.ndarray,
    sigma: np.ndarray,
    bounds: Tuple[float, float] | np.ndarray,
) -> np.ndarray:
    """Generate bounded Gaussian random-walk trajectories.

    Each trajectory starts from ``local_params[:, 0]`` and evolves via
    Gaussian increments with scale ``sigma``. Increments are cumulatively
    summed across steps, and each trajectory is mapped to ``bounds`` using
    ``scaled_sigmoid``.

    Parameters
    ----------
    local_params : np.ndarray
        Array of shape (batch_size, steps) with initial values in column 0.
    sigma : np.ndarray
        Per-trajectory standard deviation of increments (batch_size,).
    bounds : tuple or array-like
        Two-elements specifying output limits.

    Returns
    -------
    np.ndarray
        ``local_params`` containing the bounded random-walk trajectories.
    """
    batch_size, steps = local_params.shape
    lower = bounds[0]
    upper = bounds[1]

    for b in prange(batch_size):
        z = np.random.randn(steps - 1)
        local_params[b, 1:] = local_params[b, 0] + np.cumsum(sigma[b] * z)
        local_params[b, :] = scaled_sigmoid(local_params[b, :], lower, upper)
        
    return local_params


class RandomWalk(Transition):
    """Gaussian random walk transition.

    Each trajectory is generated by starting at an initial value drawn from
    ``initial_prior`` and repeatedly adding a Gaussian increment.  The
    resulting values are squashed to lie within ``bounds`` using a scaled
    sigmoid transform.
    """

    def __init__(
        self,
        bounds: Tuple[float, float] | np.ndarray,
        initial_prior: None | Prior = None,
        sigma: float = 0.1
    ):
        """
        Parameters
        ----------
        bounds : tuple or array-like
            Minimum and maximum allowed values for the walk.
        initial_prior : Prior, optional
            Prior distribution for the starting value.
        sigma : float, optional
            Standard deviation of the Gaussian increment per time step.
        """
        super().__init__(
            initial_prior=initial_prior,
            bounds=bounds
        )
        self.sigma = sigma

    def sample(self, batch_size: int, steps: int) -> dict:
        """Sample a batch of random-walk trajectories.

        Parameters
        ----------
        batch_size : int
            Number of trajectories to generate.
        steps : int
            Number of time steps in each trajectory.

        Returns
        -------
        dict
            Dictionary with keys ``"local_params"`` and ``"sigma"``.
        """
        local_params = np.empty((batch_size, steps), dtype=np.float32)
        local_params[:, 0] = self.initial_prior.sample(batch_size)
        sigma = np.abs(np.random.normal(0.0, self.sigma, size=batch_size))
        local_params = sample_random_walk(
            local_params,
            sigma,
            self.bounds
        )
        
        return {"local_params": local_params, "sigma": sigma}