from typing import Tuple
import numpy as np
from numba import njit, prange

from .transition import Transition
from superstats.utils.helpers import scaled_sigmoid
from superstats.prior import Prior


@njit(parallel=True)
def sample_random_walk(
    local_params: np.ndarray,
    sigma: np.ndarray,
    bounds: np.ndarray,
) -> np.ndarray:
    """Internal helper: batch Gaussian random walk update.

    This low-level function is ``@njit`` compiled for performance and is
    used by :class:`RandomWalk` to advance a set of trajectories one step at a
    time.  The computation is performed in parallel over the batch dimension.

    Parameters
    ----------
    local_params : np.ndarray
        Array of shape ``(batch_size, steps)`` containing existing values.
    sigma : np.ndarray
        One-dimensional array of length ``batch_size`` providing the scale of
        the Gaussian increment for each trajectory.
    bounds : np.ndarray
        Two-element array specifying lower and upper limits; values are
        squashed to this interval after each update.

    Returns
    -------
    np.ndarray
        The input ``local_params`` array with trajectories updated in place.
    """
    batch_size, steps = local_params.shape
    z = np.random.randn(batch_size, steps-1)
    for b in prange(batch_size):
        for t in range(1, steps):
            local_params[b, t] = local_params[b, t-1] + sigma[b] * z[b, t-1]
        local_params[b, :] = scaled_sigmoid(
            local_params[b, :], bounds[0], bounds[1]
        )
    return local_params

# implement as cumsum



class RandomWalk(Transition):
    """Gaussian random walk transition.

    Each trajectory is generated by starting at an initial value drawn from
    ``initial_prior`` and repeatedly adding a Gaussian increment.  The
    resulting values are squashed to lie within ``bounds`` using a scaled
    sigmoid transform.
    """

    def __init__(
        self,
        bounds: Tuple[float, float] | np.ndarray,
        initial_prior: None | Prior = None,
        sigma: float = 0.1
    ):
        """
        Parameters
        ----------
        bounds : tuple or array-like
            Minimum and maximum allowed values for the walk.
        initial_prior : Prior, optional
            Prior distribution for the starting value.
        sigma : float, optional
            Standard deviation of the Gaussian increment per time step.
        """
        super().__init__(
            initial_prior=initial_prior,
            bounds=bounds
        )
        self.sigma = sigma

    def sample(self, batch_size: int, steps: int) -> dict:
        """Sample a batch of random-walk trajectories.

        Parameters
        ----------
        batch_size : int
            Number of trajectories to generate.
        steps : int
            Number of time steps in each trajectory.

        Returns
        -------
        dict
            Dictionary with keys ``"local_params"`` and ``"sigma"``.
        """
        local_params = np.empty((batch_size, steps), dtype=np.float32)
        local_params[:, 0] = self.initial_prior.sample(batch_size)
        sigma = np.abs(np.random.normal(0.0, self.sigma, size=batch_size))
        local_params = sample_random_walk(
            local_params,
            sigma,
            self.bounds
        )
        
        return {"local_params": local_params, "sigma": sigma}